name: Build WF
on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Maven Build
        run: mvn install
        working-directory: app
  Testing:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Maven Test
        run: mvn test
        working-directory: app
        
      # Ikenna
      - name: Checkstyle
        run: mvn checkstyle:check
        
